# 1. Extract: Import libraries and load datasets
- Import Python libraries
- Load StatsBomb data:
    - Load 'competitions.json' into a dataframe and inspect the first few lines

In [227]:
import pandas as pd
import numpy as np
import json

### 1a. Import & analyze COMPETITIONS

In [228]:
with open('.\data\competitions.json', 'r') as datafile:
    data = json.load(datafile)
competitions = pd.DataFrame(data)

In [229]:
competitions.head()

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-07-15T14:15:54.671676,2024-07-15T14:17:00.877356,2024-07-15T14:17:00.877356,2024-07-15T14:15:54.671676
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2024-06-13T07:51:02.452825,None,None,2024-06-13T07:51:02.452825
3,16,4,Europe,Champions League,male,False,False,2018/2019,2024-06-12T07:44:38.559714,2021-06-13T16:17:31.694,None,2024-06-12T07:44:38.559714
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882

In [257]:
print("Total number of competitions:",competitions['competition_id'].count())

Total number of competitions: 74

In [258]:
competitions["competition_name"].groupby(competitions["competition_name"]).count()

competition_name
1. Bundesliga               2
African Cup of Nations      1
Champions League           18
Copa America                1
Copa del Rey                3
FA Women's Super League     3
FIFA U20 World Cup          1
FIFA World Cup              8
Indian Super league         1
La Liga                    18
Liga Profesional            2
Ligue 1                     3
Major League Soccer         1
NWSL                        1
North American League       1
Premier League              2
Serie A                     2
UEFA Euro                   2
UEFA Europa League          1
UEFA Women's Euro           1
Women's World Cup           2
Name: competition_name, dtype: int64

In [261]:
competitions[["competition_name", "season_name"]].head(10)

         competition_name season_name
0           1. Bundesliga   2023/2024
1           1. Bundesliga   2015/2016
2  African Cup of Nations        2023
3        Champions League   2018/2019
4        Champions League   2017/2018
5        Champions League   2016/2017
6        Champions League   2015/2016
7        Champions League   2014/2015
8        Champions League   2013/2014
9        Champions League   2012/2013

In [234]:
categories[categories['competition_name'] == "Champions League"].sort_values(by=['season_name'])

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
20,16,276,Europe,Champions League,male,False,False,1970/1971,2024-02-13T14:24:12.213582,None,None,2024-02-13T14:24:12.213582
19,16,71,Europe,Champions League,male,False,False,1971/1972,2024-02-12T14:25:01.735880,2021-06-13T16:17:31.694,None,2024-02-12T14:25:01.735880
18,16,277,Europe,Champions League,male,False,False,1972/1973,2024-02-13T14:25:16.532771,None,None,2024-02-13T14:25:16.532771
17,16,76,Europe,Champions League,male,False,False,1999/2000,2020-07-29T05:00,2021-06-13T16:17:31.694,None,2020-07-29T05:00
16,16,44,Europe,Champions League,male,False,False,2003/2004,2024-02-12T13:51:22.366380,2021-06-13T16:17:31.694,None,2024-02-12T13:51:22.366380
15,16,37,Europe,Champions League,male,False,False,2004/2005,2024-02-12T13:09:19.665986,2021-06-13T16:17:31.694,None,2024-02-12T13:09:19.665986
14,16,39,Europe,Champions League,male,False,False,2006/2007,2024-02-12T13:48:23.967222,2021-06-13T16:17:31.694,None,2024-02-12T13:48:23.967222
13,16,41,Europe,Champions League,male,False,False,2008/2009,2024-02-13T07:02:54.657056,2021-06-13T16:17:31.694,None,2024-02-13T07:02:54.657056
12,16,21,Europe,Champions League,male,False,False,2009/2010,2024-02-12T12:49:25.017694,2021-06-13T16:17:31.694,None,2024-02-12T12:49:25.017694
11,16,22,Europe,Champions League,male,False,False,2010/2011,2024-02-12T12:53:03.944320,2021-06-13T16:17:31.694,None,2024-02-12T12:53:03.944320
10,16,23,Europe,Champions League,male,False,False,2011/2012,2024-02-13T02:36:35.698340,2021-06-13T16:17:31.694,None,2024-02-13T02:36:35.698340
9,16,24,Europe,Champions League,male,False,False,2012/2013,2024-02-12T12:47:34.340413,2021-06-13T16:17:31.694,None,2024-02-12T12:47:34.340413
8,16,25,Europe,Champions League,male,False,False,2013/2014,2024-02-12T12:48:48.479157,2021-06-13T16:17:31.694,None,2024-02-12T12:48:48.479157
7,16,26,Europe,Champions League,male,False,False,2014/2015,2024-02-12T12:49:54.914228,2021-06-13T16:17:31.694,None,2024-02-12T12:49:54.914228
6,16,27,Europe,Champions League,male,False,False,2015/2016,2024-06-12T07:45:38.786894,2021-06-13T16:17:31.694,None,2024-06-12T07:45:38.786894
5,16,2,Europe,Champions League,male,False,False,2016/2017,2024-02-13T02:37:32.205154,2021-06-13T16:17:31.694,None,2024-02-13T02:37:32.205154
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882
3,16,4,Europe,Champions League,male,False,False,2018/2019,2024-06-12T07:44:38.559714,2021-06-13T16:17:31.694,None,2024-06-12T07:44:38.559714

In [235]:
categories[categories['competition_name'] == "La Liga"].sort_values(by=['season_name'])

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
55,11,278,Spain,La Liga,male,False,False,1973/1974,2023-07-06T12:50:48.807820,None,None,2023-07-06T12:50:48.807820
54,11,37,Spain,La Liga,male,False,False,2004/2005,2023-11-29T10:56:10.031508,2021-06-13T16:17:31.694,None,2023-11-29T10:56:10.031508
53,11,38,Spain,La Liga,male,False,False,2005/2006,2022-07-03T12:34:31.749038,2021-06-13T16:17:31.694,None,2022-07-03T12:34:31.749038
52,11,39,Spain,La Liga,male,False,False,2006/2007,2023-03-26T23:19:39.125951,2021-06-13T16:17:31.694,None,2023-03-26T23:19:39.125951
51,11,40,Spain,La Liga,male,False,False,2007/2008,2023-04-19T10:42:35.284291,2021-06-13T16:17:31.694,None,2023-04-19T10:42:35.284291
50,11,41,Spain,La Liga,male,False,False,2008/2009,2023-04-19T10:46:29.203565,2021-06-13T16:17:31.694,None,2023-04-19T10:46:29.203565
49,11,21,Spain,La Liga,male,False,False,2009/2010,2023-11-29T10:55:10.039117,2021-06-13T16:17:31.694,None,2023-11-29T10:55:10.039117
48,11,22,Spain,La Liga,male,False,False,2010/2011,2023-04-19T10:48:44.079830,2021-06-13T16:17:31.694,None,2023-04-19T10:48:44.079830
47,11,23,Spain,La Liga,male,False,False,2011/2012,2022-12-01T14:10:17.791769,2021-06-13T16:17:31.694,None,2022-12-01T14:10:17.791769
46,11,24,Spain,La Liga,male,False,False,2012/2013,2024-03-10T11:24:05.201066,2021-06-13T16:17:31.694,None,2024-03-10T11:24:05.201066
45,11,25,Spain,La Liga,male,False,False,2013/2014,2022-07-23T12:18:49.547396,2021-06-13T16:17:31.694,None,2022-07-23T12:18:49.547396
44,11,26,Spain,La Liga,male,False,False,2014/2015,2023-09-20T17:22:28.925900,2021-06-13T16:17:31.694,None,2023-09-20T17:22:28.925900
43,11,27,Spain,La Liga,male,False,False,2015/2016,2024-05-16T14:06:52.149840,2021-06-13T16:17:31.694,None,2024-05-16T14:06:52.149840
42,11,2,Spain,La Liga,male,False,False,2016/2017,2024-03-12T08:49:46.449084,2021-06-13T16:17:31.694,None,2024-03-12T08:49:46.449084
41,11,1,Spain,La Liga,male,False,False,2017/2018,2024-06-12T07:32:43.196678,2021-06-13T16:17:31.694,None,2024-06-12T07:32:43.196678
40,11,4,Spain,La Liga,male,False,False,2018/2019,2024-06-12T07:42:36.910303,2021-07-09T14:53:22.103024,None,2024-06-12T07:42:36.910303
39,11,42,Spain,La Liga,male,False,False,2019/2020,2024-07-12T16:27:54.561817,2021-06-13T16:17:31.694,None,2024-07-12T16:27:54.561817
38,11,90,Spain,La Liga,male,False,False,2020/2021,2024-07-15T15:15:28.367546,2024-07-15T15:17:45.455234,2024-07-15T15:17:45.455234,2024-07-15T15:15:28.367546

In [236]:
comp_id = categories[(categories["competition_name"] == "La Liga") & (categories["season_name"] == "2019/2020")][["competition_id", "season_id", "season_name"]]
comp_id

    competition_id  season_id season_name
39              11         42   2019/2020

### 1b. Load and analyze MATCHES of specific competition (La Liga 2019/20)

In [266]:
# Open file for specific CL season:
with open('.\data\matches\comp11\seas42.json', 'r', encoding='utf-8') as datafile:
    data = json.load(datafile)
matches = pd.json_normalize(data) # Normalizes json file, especially concerning the nested dicts in some columns!

In [267]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 42 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   match_id                        33 non-null     int64
 1   match_date                      33 non-null     object
 2   kick_off                        33 non-null     object
 3   home_score                      33 non-null     int64
 4   away_score                      33 non-null     int64
 5   match_status                    33 non-null     object
 6   match_status_360                33 non-null     object
 7   last_updated                    33 non-null     object
 8   last_updated_360                33 non-null     object
 9   match_week                      33 non-null     int64
 10  competition.competition_id      33 non-null     int64
 11  competition.country_name        33 non-null     object
 12  competition.competition_name    33 non-null     object
 13  season.season_id                33 non-null     int64
 14  season.season_name              33 non-null     object
 15  home_team.home_team_id          33 non-null     int64
 16  home_team.home_team_name        33 non-null     object
 17  home_team.home_team_gender      33 non-null     object
 18  home_team.home_team_group       0 non-null      object
 19  home_team.country.id            33 non-null     int64
 20  home_team.country.name          33 non-null     object
 21  home_team.managers              33 non-null     object
 22  away_team.away_team_id          33 non-null     int64
 23  away_team.away_team_name        33 non-null     object
 24  away_team.away_team_gender      33 non-null     object
 25  away_team.away_team_group       0 non-null      object
 26  away_team.country.id            33 non-null     int64
 27  away_team.country.name          33 non-null     object
 28  away_team.managers              33 non-null     object
 29  metadata.data_version           33 non-null     object
 30  metadata.shot_fidelity_version  33 non-null     object
 31  metadata.xy_fidelity_version    33 non-null     object
 32  competition_stage.id            33 non-null     int64
 33  competition_stage.name          33 non-null     object
 34  stadium.id                      33 non-null     int64
 35  stadium.name                    33 non-null     object
 36  stadium.country.id              33 non-null     int64
 37  stadium.country.name            33 non-null     object
 38  referee.id                      7 non-null      float64
 39  referee.name                    7 non-null      object
 40  referee.country.id              7 non-null      float64
 41  referee.country.name            7 non-null      object
dtypes: float64(2), int64(13), object(27)
memory usage: 11.0+ KB

In [331]:
match_id = matches.loc[0]["match_id"]
matches.sort_values(by="match_date", ascending=True)[["match_id", "match_week", "match_date", "home_team.home_team_name", "away_team.away_team_name", "home_score", "away_score"]].head(50)
i = 1
for idx in matches["match_id"]:
    print(i,".", idx)
    i += 1

1 . 303731
2 . 303532
3 . 303516
4 . 303596
5 . 303430
6 . 303725
7 . 303504
8 . 303451
9 . 303664
10 . 303682
11 . 303400
12 . 303634
13 . 303421
14 . 303493
15 . 303680
16 . 303479
17 . 303615
18 . 303696
19 . 303487
20 . 303600
21 . 303548
22 . 303652
23 . 303674
24 . 303470
25 . 303700
26 . 303707
27 . 303666
28 . 303715
29 . 303377
30 . 303524
31 . 303517
32 . 303610
33 . 303473

In [321]:
# 1c. Load and analyze EVENTS of specific match (match_id = 303731)
# Open file for specific CL season:
#with open('.\data\events\match303731.json', 'r', encoding='utf-8') as datafile:
with open('.\data\events\{match}.json'.format(match=match_id), 'r', encoding='utf-8') as datafile: # TODO: Replace 303731 by variable!!!
    data = json.load(datafile)
events = pd.json_normalize(data) # Normalizes json file, especially concerning the nested dicts in some columns!

In [322]:
events.shape

(3690, 120)

In [317]:
events.head()

,id,index,period,timestamp,minute,second,possession,duration,type.id,type.name,...,bad_behaviour.card.id,bad_behaviour.card.name,foul_committed.advantage,foul_won.advantage,shot.saved_off_target,goalkeeper.shot_saved_off_target,pass.straight,foul_committed.card.id,foul_committed.card.name,shot.open_goal
0,d0fdc490-0cf2-48de-a516-7e3ea6498ec8,1,1,00:00:00.000,0,0,1,0.000000,35,Starting XI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,745ef8bb-3a10-4a7c-ac36-1334e8df2d28,2,1,00:00:00.000,0,0,1,0.000000,35,Starting XI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9a32d241-b9e9-456d-8009-e3c3e44eecf0,3,1,00:00:00.000,0,0,1,0.000000,18,Half Start,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,8b5b2a66-7ef6-43bc-9dee-9bea1aba0ab4,4,1,00:00:00.000,0,0,1,0.000000,18,Half Start,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,a1f0c2db-0bfe-4a82-8d2a-fdae9e30bcc3,5,1,00:00:01.398,0,1,2,0.758743,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [293]:
events.columns.values

array(['id', 'index', 'period', 'timestamp', 'minute', 'second',
       'possession', 'duration', 'type.id', 'type.name',
       'possession_team.id', 'possession_team.name', 'play_pattern.id',
       'play_pattern.name', 'team.id', 'team.name', 'tactics.formation',
       'tactics.lineup', 'related_events', 'location', 'player.id',
       'player.name', 'position.id', 'position.name', 'pass.recipient.id',
       'pass.recipient.name', 'pass.length', 'pass.angle',
       'pass.height.id', 'pass.height.name', 'pass.end_location',
       'pass.body_part.id', 'pass.body_part.name', 'pass.type.id',
       'pass.type.name', 'carry.end_location', 'under_pressure',
       'pass.outcome.id', 'pass.outcome.name', 'ball_receipt.outcome.id',
       'ball_receipt.outcome.name', 'duel.type.id', 'duel.type.name',
       'duel.outcome.id', 'duel.outcome.name', 'clearance.right_foot',
       'clearance.body_part.id', 'clearance.body_part.name', 'off_camera',
       'pass.switch', 'interception.outcome.id',
       'interception.outcome.name', 'foul_committed.offensive',
       'foul_committed.type.id', 'foul_committed.type.name',
       'dribble.outcome.id', 'dribble.outcome.name', 'foul_won.defensive',
       'counterpress', 'out', 'block.offensive', 'pass.cross',
       'pass.assisted_shot_id', 'pass.shot_assist', 'shot.statsbomb_xg',
       'shot.end_location', 'shot.key_pass_id', 'shot.outcome.id',
       'shot.outcome.name', 'shot.type.id', 'shot.type.name',
       'shot.body_part.id', 'shot.body_part.name', 'shot.technique.id',
       'shot.technique.name', 'shot.freeze_frame',
       'goalkeeper.position.id', 'goalkeeper.position.name',
       'goalkeeper.technique.id', 'goalkeeper.technique.name',
       'goalkeeper.body_part.id', 'goalkeeper.body_part.name',
       'goalkeeper.type.id', 'goalkeeper.type.name',
       'goalkeeper.outcome.id', 'goalkeeper.outcome.name',
       'pass.cut_back', 'clearance.left_foot', 'pass.through_ball',
       'pass.technique.id', 'pass.technique.name', 'pass.aerial_won',
       'clearance.head', 'clearance.aerial_won',
       'ball_recovery.recovery_failure', 'pass.goal_assist',
       'dribble.nutmeg', 'goalkeeper.end_location', 'shot.one_on_one',
       'shot.first_time', 'pass.outswinging', '50_50.outcome.id',
       '50_50.outcome.name', 'pass.inswinging', 'pass.no_touch',
       'pass.miscommunication', 'substitution.outcome.id',
       'substitution.outcome.name', 'substitution.replacement.id',
       'substitution.replacement.name', 'bad_behaviour.card.id',
       'bad_behaviour.card.name', 'foul_committed.advantage',
       'foul_won.advantage', 'shot.saved_off_target',
       'goalkeeper.shot_saved_off_target', 'pass.straight',
       'foul_committed.card.id', 'foul_committed.card.name',
       'shot.open_goal'], dtype=object)

In [285]:
print("Columns of event_df:\n",events["goalkeeper.type.name"].count())

Columns of event_df:
 27

In [302]:
events[(events["goalkeeper.type.name"].notnull()) & (events["goalkeeper.type.name"] == "Goal Conceded")][["minute", "second", "period", "possession_team.name", "goalkeeper.type.id", "goalkeeper.type.name"]]

,minute,second,period,possession_team.name,goalkeeper.type.id,goalkeeper.type.name
694,13,47,1,Barcelona,26.0,Goal Conceded
1698,36,54,1,Barcelona,26.0,Goal Conceded
1759,39,20,1,Eibar,26.0,Goal Conceded
3493,86,55,2,Barcelona,26.0,Goal Conceded
3558,88,48,2,Barcelona,26.0,Goal Conceded

In [310]:
events[(events["minute"] == 39)].sort_values(by="timestamp", ascending=True)

,id,index,period,timestamp,minute,second,possession,duration,type.id,type.name,...,bad_behaviour.card.id,bad_behaviour.card.name,foul_committed.advantage,foul_won.advantage,shot.saved_off_target,goalkeeper.shot_saved_off_target,pass.straight,foul_committed.card.id,foul_committed.card.name,shot.open_goal
1741,acab6bc7-2fc5-4d7b-9d55-8ffc99a01cab,1742,1,00:39:06.156,39,6,76,2.207054,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1742,99049f38-044e-4807-827d-cf74d44b4a45,1743,1,00:39:08.363,39,8,76,NaN,42,Ball Receipt*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1743,8661854b-988d-4e93-a56e-96dc2543a74e,1744,1,00:39:08.936,39,8,76,1.937588,17,Pressure,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1744,b64209ae-b928-4de3-9a4d-92ad7eef7957,1745,1,00:39:10.971,39,10,76,1.101217,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1745,cbaa5ed0-85d6-4028-bc05-21783e302cc3,1746,1,00:39:12.073,39,12,76,NaN,42,Ball Receipt*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1746,a6a7ad44-0227-4cac-a409-aa2b1b9d8f86,1747,1,00:39:12.073,39,12,76,1.388413,43,Carry,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1747,f8278964-a27a-4605-8212-437d3ad9a526,1748,1,00:39:12.430,39,12,76,1.057436,17,Pressure,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1748,15946fd2-e09a-4ffe-9a20-7284ffeca125,1749,1,00:39:13.461,39,13,76,0.073987,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1749,7521f6f9-611a-49cc-8b41-584144d4c7d8,1750,1,00:39:13.535,39,13,76,0.000000,6,Block,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1751,249e1de3-f61b-4f66-bd06-ae986b1dceca,1752,1,00:39:15.009,39,15,76,2.317172,43,Carry,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1750,269af134-723b-4752-b4cf-d347b399d8f7,1751,1,00:39:15.009,39,15,76,0.000000,2,Ball Recovery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1752,34cfe88a-1238-4152-9abd-a5ba9eede31d,1753,1,00:39:17.326,39,17,76,0.861217,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1753,04f197b8-34ec-4c55-a878-033e6da6f8ff,1754,1,00:39:18.188,39,18,76,NaN,42,Ball Receipt*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1754,e73c4f39-16f1-407a-95d3-9c9a0f6e9f0e,1755,1,00:39:18.188,39,18,76,0.081597,43,Carry,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1755,e8d7c2a2-1b96-4309-a60e-77e5bd953857,1756,1,00:39:18.269,39,18,76,0.000000,38,Miscontrol,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1756,1aa0ada2-5d5d-4b72-b0f3-c9101f31a983,1757,1,00:39:18.903,39,18,76,0.000000,2,Ball Recovery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1757,34c1601a-3a16-4458-b467-73a149a2c23f,1758,1,00:39:19.871,39,19,76,0.000000,2,Ball Recovery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1758,1c0c7ac1-f01c-4f6d-9c51-3e97154fa119,1759,1,00:39:19.911,39,19,76,0.728709,16,Shot,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1759,e59339f7-0e98-42f3-9350-6320384c0080,1760,1,00:39:20.639,39,20,76,0.000000,23,Goal Keeper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [312]:
events[events["id"] == "1c0c7ac1-f01c-4f6d-9c51-3e97154fa119"].values

array([['1c0c7ac1-f01c-4f6d-9c51-3e97154fa119', 1759, 1, '00:39:19.911',
        39, 19, 76, 0.728709, 16, 'Shot', 322, 'Eibar', 3,
        'From Free Kick', 217, 'Barcelona', nan, nan,
        list(['e59339f7-0e98-42f3-9350-6320384c0080']),
        list([110.5, 43.7]), 5503.0, 'Lionel Andrés Messi Cuccittini',
        17.0, 'Right Wing', nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, 0.32442024, list([120.0, 39.6, 0.3]),
        nan, 97.0, 'Goal', 87.0, 'Open Play', 38.0, 'Left Foot', 93.0,
        'Normal',
        list([{'location': [104.0, 56.2], 'player': {'id': 5470, 'name': 'Ivan Rakitić'}, 'position': {'id': 13, 'name': 'Right Center Midfield'}, 'teammate': True}, {'location': [110.0, 35.6], 'player': {'id': 5487, 'name': 'Antoine Griezmann'}, 'position': {'id': 23, 'name': 'Center Forward'}, 'teammate': True}, {'location': [112.1, 30.8], 'player': {'id': 8206, 'name': 'Arturo Erasmo Vidal Pardo'}, 'position': {'id': 21, 'name': 'Left Wing'}, 'teammate': True}, {'location': [113.3, 39.9], 'player': {'id': 6698, 'name': 'Marko Dmitrović'}, 'position': {'id': 1, 'name': 'Goalkeeper'}, 'teammate': False}, {'location': [102.0, 56.8], 'player': {'id': 6705, 'name': 'José Ángel Valdés Díaz'}, 'position': {'id': 6, 'name': 'Left Back'}, 'teammate': False}, {'location': [103.0, 52.6], 'player': {'id': 6709, 'name': 'Anaitz Arbilla Zabala'}, 'position': {'id': 5, 'name': 'Left Center Back'}, 'teammate': False}, {'location': [89.0, 66.6], 'player': {'id': 6910, 'name': 'Eduardo Expósito Jaén'}, 'position': {'id': 11, 'name': 'Left Defensive Midfield'}, 'teammate': False}, {'location': [113.9, 42.6], 'player': {'id': 23803, 'name': 'Esteban Rodrigo Burgos'}, 'position': {'id': 3, 'name': 'Right Center Back'}, 'teammate': False}, {'location': [111.3, 40.7], 'player': {'id': 23981, 'name': 'Álvaro Tejero Sacristán'}, 'position': {'id': 2, 'name': 'Right Back'}, 'teammate': False}]),
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, True, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan]], dtype=object)

In [311]:
events[events["id"] == "e59339f7-0e98-42f3-9350-6320384c0080"].values

array([['e59339f7-0e98-42f3-9350-6320384c0080', 1760, 1, '00:39:20.639',
        39, 20, 76, 0.0, 23, 'Goal Keeper', 322, 'Eibar', 3,
        'From Free Kick', 322, 'Eibar', nan, nan,
        list(['1c0c7ac1-f01c-4f6d-9c51-3e97154fa119']),
        list([6.8, 40.2]), 6698.0, 'Marko Dmitrović', 1.0, 'Goalkeeper',
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        42.0, 'Moving', 45.0, 'Diving', nan, nan, 26.0, 'Goal Conceded',
        55.0, 'No Touch', nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]],
      dtype=object)

In [305]:
events[(events["minute"] == 13)].sort_values(by="timestamp", ascending=True)

,id,index,period,timestamp,minute,second,possession,duration,type.id,type.name,...,bad_behaviour.card.id,bad_behaviour.card.name,foul_committed.advantage,foul_won.advantage,shot.saved_off_target,goalkeeper.shot_saved_off_target,pass.straight,foul_committed.card.id,foul_committed.card.name,shot.open_goal
643,66daf985-76c5-4599-ad11-e8f4e4a080a8,644,1,00:13:00.051,13,0,25,NaN,42,Ball Receipt*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
644,02452511-fa8d-401a-8a5f-b51ba9f71712,645,1,00:13:00.051,13,0,25,1.395731,43,Carry,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
645,ca766729-339a-4d36-8700-69d1b6d06a48,646,1,00:13:01.446,13,1,25,1.256129,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
646,ed2a2230-83ae-4724-a689-9340760f9dc6,647,1,00:13:02.703,13,2,25,NaN,42,Ball Receipt*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
647,6f47624a-8dd5-4d29-85bc-d2804776c911,648,1,00:13:02.703,13,2,25,2.934371,43,Carry,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
648,562374f4-18cf-4116-ba3b-6a3521de7b6e,649,1,00:13:05.637,13,5,25,0.847353,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
649,3e6d74b6-e4a5-4d87-99ed-f70f3a8ea1d3,650,1,00:13:06.484,13,6,25,NaN,42,Ball Receipt*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
650,6a133274-648e-45fa-9154-8f7d4ae84399,651,1,00:13:06.484,13,6,25,1.014616,43,Carry,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
651,a61e7e7f-67b9-41fb-90ef-4eab5dd98ff1,652,1,00:13:07.499,13,7,25,1.414903,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
652,877e2222-4c02-4515-8708-8ca602dd74d5,653,1,00:13:08.914,13,8,25,NaN,42,Ball Receipt*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
653,83d7d09e-59c2-4f88-a811-ad063886c470,654,1,00:13:08.914,13,8,25,1.979432,43,Carry,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
654,26e7938a-3c19-4bb6-ae25-adb672629b5d,655,1,00:13:10.893,13,10,25,0.891733,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
656,8ab216d5-890f-4acc-b276-84bb6a8e6bbe,657,1,00:13:11.785,13,11,25,3.529865,43,Carry,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
655,24b6f4d6-7c0a-4389-90f1-71fcd2cca85f,656,1,00:13:11.785,13,11,25,NaN,42,Ball Receipt*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
657,b21daf0b-b1e7-4604-9de4-b416752fca70,658,1,00:13:15.315,13,15,25,2.286776,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
658,148e54a4-4a4f-462c-a8da-5a8c3f584eb3,659,1,00:13:17.602,13,17,25,NaN,42,Ball Receipt*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
659,d3b52fe6-bce2-4cb6-b56e-ae565c0f76fe,660,1,00:13:17.602,13,17,25,1.712547,43,Carry,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
660,15703889-7148-40b4-9ca2-279a91b2bb4b,661,1,00:13:19.314,13,19,25,1.005585,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
661,46049809-c121-4108-a514-f7dbd3f047ae,662,1,00:13:20.320,13,20,25,NaN,42,Ball Receipt*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
662,769f022b-cca0-42bd-b617-9e66bb1ffaf4,663,1,00:13:20.320,13,20,25,1.299344,43,Carry,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
663,30988d54-c8cd-4993-8b52-8eb57603dfd7,664,1,00:13:21.619,13,21,25,0.665698,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
664,e21f849e-f729-4709-b9cd-9a40c4ef5b86,665,1,00:13:22.285,13,22,25,NaN,42,Ball Receipt*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
665,e0442536-9af7-4e19-b824-c3e3fa4454e4,666,1,00:13:22.285,13,22,25,0.861600,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
666,bac0bff1-a323-4754-b2a3-550a346594df,667,1,00:13:23.146,13,23,25,NaN,42,Ball Receipt*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
667,31aaae10-0c14-4b15-95ef-ec9fae6e5360,668,1,00:13:23.146,13,23,25,0.589712,43,Carry,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
668,04a6552d-b5dd-4e84-8d70-ed4ebbdd1bd2,669,1,00:13:23.736,13,23,25,1.095048,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
669,5cd5c9a1-2247-4142-87a2-cc2d64158384,670,1,00:13:24.831,13,24,25,NaN,42,Ball Receipt*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
670,84f48761-3640-4f60-b1ca-d1b7ac677c6a,671,1,00:13:24.831,13,24,25,0.000000,10,Interception,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
671,4c087c2e-fbfe-43d9-829e-dbd6d25f20fd,672,1,00:13:25.972,13,25,26,1.061352,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
672,f76e51dc-139e-45b7-87d5-939d4f140744,673,1,00:13:26.494,13,26,26,0.706716,17,Pressure,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
673,f2c4af26-b6ad-4bad-82e6-86ce3c77ba06,674,1,00:13:27.033,13,27,26,NaN,42,Ball Receipt*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
674,4a04be3a-7727-424e-a0b2-363a0e745ad0,675,1,00:13:27.033,13,27,26,0.103126,43,Carry,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
675,7165b271-edc2-493a-afb9-b014ce21bee2,676,1,00:13:27.137,13,27,26,2.392599,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
676,b0726c1c-bea4-4bfd-a6cc-704f2e25d77b,677,1,00:13:29.529,13,29,26,NaN,42,Ball Receipt*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
677,2f347c51-a9eb-4e25-ba36-6e176b732233,678,1,00:13:29.529,13,29,26,0.301686,43,Carry,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
678,e170a4cb-8ecb-4733-b69c-36daeb406fae,679,1,00:13:29.831,13,29,26,0.000000,38,Miscontrol,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
679,94f91128-3913-480c-b74d-01f29ab2ab99,680,1,00:13:33.165,13,33,27,1.309867,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
681,49f5efa5-af40-4943-8e2a-92a484c1b22d,682,1,00:13:34.475,13,34,27,5.041737,43,Carry,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
680,74d1908e-d76f-4ebf-9e64-3b06991e133a,681,1,00:13:34.475,13,34,27,NaN,42,Ball Receipt*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
682,93148fd3-58f5-403d-b3b4-6e9626808f50,683,1,00:13:39.517,13,39,27,1.156243,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
683,b5a0f340-5bfa-49f8-9ac8-7a332c12aef5,684,1,00:13:40.673,13,40,27,NaN,42,Ball Receipt*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
684,3b29c924-5ae3-486c-aa27-f50d67d00e37,685,1,00:13:40.673,13,40,27,1.088250,43,Carry,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
685,5c227063-fa17-4b80-b23b-88169fc869ba,686,1,00:13:41.761,13,41,27,0.635604,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
686,1b4bbe23-c07a-4e4b-8a4d-fe3d496116d2,687,1,00:13:42.397,13,42,27,NaN,42,Ball Receipt*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
687,7bf58475-f156-449e-abfd-b7a9572bcfc1,688,1,00:13:42.397,13,42,27,2.236129,43,Carry,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
688,8fa1b558-7529-402a-901b-28c479669c63,689,1,00:13:43.799,13,43,27,0.407399,17,Pressure,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
689,d26f5b45-ba2f-4254-8b93-1fe32fc71c1a,690,1,00:13:44.633,13,44,27,0.000000,39,Dribbled Past,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
690,87a8b8e4-155a-4411-b361-73181cb531f1,691,1,00:13:44.633,13,44,27,0.000000,14,Dribble,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
691,086c32a4-101a-4fdb-9663-0da27461f756,692,1,00:13:44.633,13,44,27,1.323036,43,Carry,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
692,f8111759-d08c-4d5a-a247-96ad9637e2d8,693,1,00:13:45.183,13,45,27,0.693594,17,Pressure,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
693,cf0fc241-1826-4478-abde-b9780d25e125,694,1,00:13:45.956,13,45,27,1.186072,16,Shot,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
694,a06fb730-bef3-4738-a024-285b9656821b,695,1,00:13:47.142,13,47,27,0.000000,23,Goal Keeper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [307]:
events[events["id"] == "cf0fc241-1826-4478-abde-b9780d25e125"].values

array([['cf0fc241-1826-4478-abde-b9780d25e125', 694, 1, '00:13:45.956',
        13, 45, 27, 1.186072, 16, 'Shot', 217, 'Barcelona', 4,
        'From Throw In', 217, 'Barcelona', nan, nan,
        list(['a06fb730-bef3-4738-a024-285b9656821b']),
        list([106.0, 34.8]), 5503.0, 'Lionel Andrés Messi Cuccittini',
        17.0, 'Right Wing', nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, 0.38735494, list([120.0, 43.5, 0.6]),
        '5c227063-fa17-4b80-b23b-88169fc869ba', 97.0, 'Goal', 87.0,
        'Open Play', 38.0, 'Left Foot', 93.0, 'Normal',
        list([{'location': [108.4, 50.7], 'player': {'id': 5487, 'name': 'Antoine Griezmann'}, 'position': {'id': 23, 'name': 'Center Forward'}, 'teammate': True}, {'location': [89.8, 58.8], 'player': {'id': 6374, 'name': 'Nélson Cabral Semedo'}, 'position': {'id': 2, 'name': 'Right Back'}, 'teammate': True}, {'location': [89.9, 44.8], 'player': {'id': 5470, 'name': 'Ivan Rakitić'}, 'position': {'id': 13, 'name': 'Right Center Midfield'}, 'teammate': True}, {'location': [104.4, 25.0], 'player': {'id': 8206, 'name': 'Arturo Erasmo Vidal Pardo'}, 'position': {'id': 21, 'name': 'Left Wing'}, 'teammate': True}, {'location': [114.9, 38.6], 'player': {'id': 6698, 'name': 'Marko Dmitrović'}, 'position': {'id': 1, 'name': 'Goalkeeper'}, 'teammate': False}, {'location': [106.8, 40.3], 'player': {'id': 6705, 'name': 'José Ángel Valdés Díaz'}, 'position': {'id': 6, 'name': 'Left Back'}, 'teammate': False}, {'location': [106.0, 35.9], 'player': {'id': 6867, 'name': 'Papa Kouly Diop'}, 'position': {'id': 9, 'name': 'Right Defensive Midfield'}, 'teammate': False}, {'location': [103.7, 32.0], 'player': {'id': 23981, 'name': 'Álvaro Tejero Sacristán'}, 'position': {'id': 2, 'name': 'Right Back'}, 'teammate': False}, {'location': [98.3, 34.1], 'player': {'id': 23803, 'name': 'Esteban Rodrigo Burgos'}, 'position': {'id': 3, 'name': 'Right Center Back'}, 'teammate': False}, {'location': [99.0, 35.1], 'player': {'id': 6709, 'name': 'Anaitz Arbilla Zabala'}, 'position': {'id': 5, 'name': 'Left Center Back'}, 'teammate': False}, {'location': [95.9, 31.8], 'player': {'id': 6910, 'name': 'Eduardo Expósito Jaén'}, 'position': {'id': 11, 'name': 'Left Defensive Midfield'}, 'teammate': False}, {'location': [91.8, 43.2], 'player': {'id': 5687, 'name': 'Takashi Inui'}, 'position': {'id': 21, 'name': 'Left Wing'}, 'teammate': False}]),
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan]], dtype=object)

In [309]:
events[events["id"] == "a06fb730-bef3-4738-a024-285b9656821b"].values

array([['a06fb730-bef3-4738-a024-285b9656821b', 695, 1, '00:13:47.142',
        13, 47, 27, 0.0, 23, 'Goal Keeper', 217, 'Barcelona', 4,
        'From Throw In', 322, 'Eibar', nan, nan,
        list(['cf0fc241-1826-4478-abde-b9780d25e125']),
        list([5.2, 41.5]), 6698.0, 'Marko Dmitrović', 1.0, 'Goalkeeper',
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        44.0, 'Set', 45.0, 'Diving', nan, nan, 26.0, 'Goal Conceded',
        55.0, 'No Touch', nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]],
      dtype=object)

In [194]:
#events[events['type'] == "{'id': 26, 'name': 'Goal Conceded'}"]
goalkeeper_events = dict()
goalkeeper_events = events["goalkeeper"]
goalkeeper_events.info()

AttributeError: 'Series' object has no attribute 'info'

In [152]:
fouls_dict = dict()
fouls_dict = events['foul_won'].groupby(events['foul_won'])

In [155]:
print(fouls_dict.items())

AttributeError: 'SeriesGroupBy' object has no attribute 'items'